name: Release worker-prod

on:
  push:
    branches: worker
    
  workflow_dispatch:

jobs:
  push_to_registry:
  runs-on: ubuntu-latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: xburrow/analysis-worker:latest-prod
          push: true
          file: ./analysis-worker/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}